import streamlit as st
import os
from langchain_core.messages import HumanMessage, AIMessage
from src.graph import app as workflow_app

# 设置页面配置
st.set_page_config(
    page_title="法律文档智能问答系统 (SmartLaw-QA)",
    page_icon="⚖️",
    layout="wide",
)

st.title("⚖️ 法律智能问答系统 (SmartLaw-QA)")
st.markdown("由于底层需要调用 Router、Researcher、Legal Consultant 多个 Agent 进行分析，检索过程可能需要一些时间，请耐心等待。")

# 初始化会话状态存取聊天记录
if "messages" not in st.session_state:
    st.session_state.messages = []

# 渲染历史聊天记录
for msg in st.session_state.messages:
    if isinstance(msg, HumanMessage):
        st.chat_message("user").write(msg.content)
    elif isinstance(msg, AIMessage):
        st.chat_message("assistant").write(msg.content)

# 监听用户输入
if user_input := st.chat_input("您可以向我提问关于法律合同、借款等相关的内容..."):
    # 显示用户问题并存入状态
    st.session_state.messages.append(HumanMessage(content=user_input))
    st.chat_message("user").write(user_input)

    # 显示处理中的动画
    with st.chat_message("assistant"):
        response_placeholder = st.empty()
        status_container = st.container()
        
        with status_container:
            with st.spinner("思考分析中..."):
                inputs = {"messages": st.session_state.messages.copy()}
                
                final_answer = ""
                # 遍历图的执行结果
                config = {"configurable": {"thread_id": "test01"}}
                for output in workflow_app.stream(inputs,config=config):
                    for node_name, result in output.items():
                        st.toast(f"✅ 完成节点分析: {node_name}")
                        
                        # 如果是最后返回的信息，通常包含最新的 AIMessage
                        # Extract AI response generated by the node
                        if "messages" in result:
                            # 拿到图执行该步骤新返回出来的 message (一般是单个 message 对象作为列表元素返回)
                            messages = result["messages"]
                            for m in reversed(messages):
                                if hasattr(m, "content"):
                                    final_answer = m.content
                                    break
                                elif isinstance(m, str):
                                    final_answer = m
                                    break
                        elif "next_agent" in result and result["next_agent"] == "FINISH":
                            # 取 Router 顺带输出的内容做回答
                            # 但是当前 router 除了分类没返回具体内容，可以添加一句提示或者直接去拿 router.invoke(query).content
                            pass
                            
                        # 如果没有在上面提取到，从 result 本身看是否有 text
                        if not final_answer and isinstance(result, str):
                            final_answer = result
                            
                # 展示最终的回答
                response_placeholder.markdown(final_answer)
                
                # 将助手的回答保存到状态，以便下次刷新使用
                if final_answer:
                    st.session_state.messages.append(AIMessage(content=final_answer))
